IT_JOBS = [
    "AI Engineer",
    "Artificial Intelligence Engineer",
    "Machine Learning Engineer",
    "Data Scientist",
    "Data Analyst",
    "Business Intelligence Analyst",
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Python Developer",
    "Java Developer",
    "Java Backend Developer",
    "Web Developer",
    "Mobile App Developer",
    "Android Developer",
    "iOS Developer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Cloud Architect",
    "Cybersecurity Analyst",
    "Security Engineer",
    "Network Engineer",
    "Database Administrator",
    "Database Engineer",
    "Data Engineer",
    "Big Data Engineer",
    "AI Research Scientist",
    "Computer Vision Engineer",
    "NLP Engineer",
    "Deep Learning Engineer",
    "MLOps Engineer",
    "QA Engineer",
    "Automation Test Engineer",
    "Embedded Systems Engineer",
    "IoT Engineer",
    "Blockchain Developer",
    "Game Developer",
    "UI/UX Designer",
    "Product Manager",
    "Solutions Architect",
    "System Administrator",
    "Site Reliability Engineer",
    "Technical Support Engineer",
    "IT Consultant",
    "IT Project Manager"
]